baseURL: https://oshw-tokyo.github.io/site-badminton-relation-bunkyo
defaultContentLanguage: ja

languages:
  ja:
    languageName: Japanese
    weight: 10
    # title: 日本むかし話
  en:
    languageName: English
    weight: 20
    # title: "Japanese Old Tales"

#deployment
publishdir: docs

title: Here is the title 1... Preparing
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: About Us
    weight: 1
    url: /about
  - name: Schedule
    weight: 2
    url: /schedule
  - name: Site
    weight: 3
    url: /site    
  - name: Contact
    weight: 4
    url: /contact

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo

